<?php

function audiotext_field_formatter_info() {
    return array(
        'audiotext' => array(
          'label' => t('Textfield URL Audio'),
          'description' => t('Display text as audio'),
          'field types' => array('text','computed', 'textfield'),
        ),
        'linktext' => array(
          'label' => t('Textfield Link'),
          'description' => t('Display text as link'),
          'field types' => array('text','computed', 'textfield'),
        ),

    );
}

function audiotext_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  $settings = $display['settings'];

  switch ($display['type']) {
    case 'audiotext':
      // Common case: each value is displayed individually in a sub-element
      // keyed by delta. The field.tpl.php template specifies the markup
      // wrapping each value.
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#markup' => '<audio controls="controls">'
          . '<source src="' . $item['value'] . '" type="audio/mpeg">'
          . 'Your browser does not support HTML5 audio.</audio> <br />'
          . '<a href="' . $item['value'] . '">(download)</a>'
        );
      }
      break;
    case 'linktext':
      // Common case: each value is displayed individually in a sub-element
      // keyed by delta. The field.tpl.php template specifies the markup
      // wrapping each value.
      foreach ($items as $delta => $item) {
        $element[$delta] = array('#markup' => l($item['value'], $item['value']));
      }
      break;


  }

  return $element;
}